export const currency = {
  AED: { name: "UAE Dirham", symbol: "AED" , flag: "🇦🇪" },
  ARS: { name: "Argentine Peso", symbol: "ARS$", flag: "🇦🇷" },
  AUD: { name: "Australian Dollar", symbol: "A$", flag: "🇦🇺" },
  BRL: { name: "Brazilian Real", symbol: "R$", flag: "🇧🇷" },
  CAD: { name: "Canadian Dollar", symbol: "C$", flag: "🇨🇦" },
  CHF: { name: "Swiss Franc", symbol: "Fr", flag: "🇨🇭" },
  CLP: { name: "Chilean Peso", symbol: "CLP$", flag: "🇨🇱" },
  CNY: { name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳" },
  COP: { name: "Colombian Peso", symbol: "COL$", flag: "🇨🇴" },
  CZK: { name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿" },
  DKK: { name: "Danish Krone", symbol: "kr", flag: "🇩🇰" },
  EGP: { name: "Egyptian Pound", symbol: "£", flag: "🇪🇬" },
  EUR: { name: "Euro", symbol: "€", flag: "🇪🇺" },
  GBP: { name: "British Pound", symbol: "£", flag: "🇬🇧" },
  HKD: { name: "Hong Kong Dollar", symbol: "HK$", flag: "🇭🇰" },
  HUF: { name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩" },
  ILS: { name: "Israeli Shekel", symbol: "₪", flag: "🇮🇱" },
  INR: { name: "Indian Rupee", symbol: "₹", flag: "🇮🇳" },
  JPY: { name: "Japanese Yen", symbol: "¥", flag: "🇯🇵" },
  KES: { name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪" },
  KRW: { name: "South Korean Won", symbol: "₩", flag: "🇰🇷" },
  MXN: { name: "Mexican Peso", symbol: "$", flag: "🇲🇽" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾" },
  NGN: { name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬" },
  NOK: { name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴" },
  NZD: { name: "New Zealand Dollar", symbol: "NZ$", flag: "🇳🇿" },
  Other: { name: "Other", symbol: "¤", flag: "🏴‍☠️" },
  PEN: { name: "Peruvian Sol", symbol: "S/", flag: "🇵🇪" },
  PHP: { name: "Philippine Peso", symbol: "₱", flag: "🇵🇭" },
  PLN: { name: "Polish Złoty", symbol: "zł", flag: "🇵🇱" },
  RUB: { name: "Russian Ruble", symbol: "₽", flag: "🇷🇺" },
  SAR: { name: "Saudi Riyal", symbol: "﷼", flag: "🇸🇦" },
  SEK: { name: "Swedish Krona", symbol: "kr", flag: "🇸🇪" },
  SGD: { name: "Singapore Dollar", symbol: "S$", flag: "🇸🇬" },
  THB: { name: "Thai Baht", symbol: "฿", flag: "🇹🇭" },
  TRY: { name: "Turkish Lira", symbol: "₺", flag: "🇹🇷" },
  USD: { name: "US Dollar", symbol: "$", flag: "🇺🇸" },
  ZAR: { name: "South African Rand", symbol: "R", flag: "🇿🇦" }
};
